# TEMPERATURE CONFIGURATION
MAX_TEMPERATURE = 70

# PIN CONFIGURATION
LED_DATA_PIN = 25
INPUT_PIN_1 = 19
INPUT_PIN_2 = 22
INPUT_PIN_3 = 23

# LEDS CONFIGURATION
NUMBER_OF_LEDS = 25

# WiFi configuration
SSID = "Burdel Laguna"
PSWD = "6G9dry5K3"
